### ISSUE TITLE
[Question] How to disable "individual" diagnostic messages

### ISSUE THREAD

**Issue by jesusramondovale** [ros/diagnostics#302]
Hi! I'm using this great package on my Ubuntu 22.04-ROS2 Humble in order to diagnostic my robot's hardware: 

    - Sick LiDAR scanner
    - Realsense Camera D455
    
Both publish a standard Diagnostic Msg on /diagnostics, so I'm using the aggregator to get a SICK unique state and a Camera unique state, and they do appear on /diagnostics_agg topic, but also on that topic is being published the 6 different diagnostic status of the camera (one per sensor) 

Is there any way to disable this and make only appear on /diagnostics_agg the aggregated ones (one item per different hardware) 

Thank you!

**Comment by jesusramondovale** [comment]
More info: I wanna see only the [0]th and [8]th item of the DiagnosticStatus sequence that is being published :

![image](https://user-images.githubusercontent.com/71335809/235890401-a38caadf-0111-4ab8-9b34-0204dc528b06.png)

**Comment by ct2034** [comment]
Hi @jesusramondovale.

I think the best approach would be to write a custom aggregator: https://github.com/ros/diagnostics/tree/ros2/diagnostic_aggregator#analyzers

There is not really a mechanism to change the diagnostic topic itself. The assumption is, that the topic contains everything you may be interested in, and you can use the aggregator to make it more readable and increase interpretability.

Hope this helps. Otherwise, feel free to open another issue.

**Comment by g-gemignani** [comment]
I guess the message was directed to @jesusramondovale  ;)
Thanks for the answer @ct2034!

**Comment by ct2034** [comment]
Haha sorry. This was the wrong mention :)
